### ISSUE TITLE
Make all settings persistent after restart

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#120]
### Is your feature request related to a problem? Please describe.
I change the Inara-Update Delay when starting to check every 5 minutes instead of 15 seconds. This setting does not persist across restarts

### Describe the solution you'd like
make all settings persistent

### Describe alternatives you've considered
Manually setting after each restart

### Additional context
![Snag_6c52676](https://user-images.githubusercontent.com/6474337/205438572-128dd77c-a1f3-408a-b1c6-70a01999f652.png)

**Comment by Fi0x** [comment]
Thank you for the report! I'll look into that as soon as I can.

Btw.: Such a high delay might cause very long waiting times until your local database is up-to date again. That's because the inara-requests mentioned here, only updates one commodity at a time (always the least recently updated one). This won't be a problem if you keep the tool running for a while, but for ~200 commodities, it will take over 16 hours to update all information when the tool was offline for a few hours. (Don't worry, the EDDN data the tool receives is the same as that from inara, it only stores live-data instead of the already gathered information you can pull from inara)

**Comment by Fi0x** [comment]
v2.1.1.0 stores the time.
I also removed the drop-down, since 60s delay should be more than enough (>3h update time for all commodities)
