### ISSUE TITLE
Carrier Profit is incorrect

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#121]
### Describe the bug
Carrier profit is reporting as 0.00 for some combinations (see screen shot)

### To Reproduce
**Version**: 2.1.1.0
**Steps to reproduce the behavior**:
1. ...

### Expected behavior
...

### Screenshots

![Snag_8677e3a](https://user-images.githubusercontent.com/6474337/205457535-d82f93bc-53bf-42a8-a5f7-284104d44832.png)

### Additional context
...

**Comment by msteele999** [comment]
Seems to be when the Galactic average is set below 1,140!

Weird

**Comment by Fi0x** [comment]
That's a safety feature and not a bug:

The game only allows your carrier prices to be at least 5% and at most 1000% of the galactic average price.

In your first screenshot you have Bauxite selected, which has a galactic average price of 1140cr.
Buying it at at Klein Survey for 10682cr would reqire your carrier buy price to be at 22682cr to give the traders the 12000cr/t profit you selected in the settings.
The maximum price to buy you can select on your carrier is 11400cr (1000% gal. avg. of Bauxite), so the tool uses this price as the `Buy Price`.
I'm not sure why the sell-price is 11400cr as well, because that should be lower to give the 12000cr profit to the unloading traders.

I'll look into this to see if I can find out what's wrong with my logic.

**Comment by msteele999** [comment]
That makes all kinds of sense!

sent from my mobile device.
