### ISSUE TITLE
[bug] Explorer's Anchorage is a valid sell station

### ISSUE THREAD

**Issue by noirscape** [Fi0x/EDCT#45]
### Describe the bug
When calculating trades, Explorer's Anchorage is considered to be a valid destination. This being in spite of the fact that Explorer's Anchorage is several thousand light years outside of the bubble and shouldn't be a profitable destination. I would suggest also similarly filtering Colonia, but generally speaking the Colonia markets are already collapsed and overfed to begin with so they shouldn't be a problem.

### To Reproduce
**Version**: 1.1.3.3
**Steps to reproduce the behavior**:
1. Open the game.
2. Get a trade.
3. Trade Destination is Explorers Anchorage.

### Expected behavior
Trade Destinations should not be Explorer's Anchorage

### Screenshots
![image](https://user-images.githubusercontent.com/13433513/122651925-21307980-d13c-11eb-8137-75c93b7f9ee9.png)

**Comment by Fi0x** [comment]
For stations like that I added the distance field below the profit, so you can see how far away the trade would take you.
![image](https://user-images.githubusercontent.com/58072122/122672224-b5492200-d1ca-11eb-88eb-d25311ab09a5.png)

I will try to add a filter option for this stat, but due to the current way the distance is received this requires a bigger re-make, which will not happen soon.

**Comment by bankshot** [comment]
If you add a max distance filter it would also allow exclusion of Rackham's Peak, which always takes the top spots unless I uncheck "include small pads"  

Or less elegantly you could add a checkbox for "include outside the bubble" which would exclude those two stations but that will introduce an ongoing maintenance issue as additional stations are added far from the bubble.

**Comment by Fi0x** [comment]
The main problem with the distance calculation is that it's only triggered if you check a trade. That's why there is alway an `UNKNOWN` distance when you first look at a trade and after a few seconds it switches to the actual distance.

**In the background the following happens:**
1. User looks at a new trade
2. Tool checks which systems are involved
3. Tool checks if local database contains distance information about those systems
4. If distance is not available locally, the tool makes a web-request which creates a notable delay

That means that if the distance check is done whenever the filter options change or the `Reload Trades` button is pressed, it would take a few minutes to get the distance between all valid stations.

**So the solutions I thought about are:**
- A filter option for the maximum distance to a specified star system
  - User can specify to which system the distance should be calculated
  - User can specify how far away from that system the trade systems can be
  - This would enable me to add a distance web-request whenever a new system gets stored in the local database
- Store the coordinates of each system
  - This allows me to calculate the distance myself, which wouldn't require a slow web-request
  - This would allow the user to filter for max distances AND max distance to a specified system

I'll work on this as soon as I did a rework of the database structure

**Comment by Fi0x** [comment]
I remade the whole database and added coordinates to the systems, but for performance reasons it's not possible to filter out systems that are too far away from each other, because I would need to calculate all distances between all stations at runtime, which is not possible.

I also tried to add a "Sol"-Filter that ignores systems that are too far away from Sol, but the performance impact for this feature is also way too high.

The last solution I currently see is to implement a black-list where you can add or remove individual stations.
**But if you have any other ideas, please let me know.**

**Comment by bankshot** [comment]
A user-editable blacklist is probably the best way to go - it lets people pick and choose what stations they don't want to see.  But if you don't want to go there I do have an idea for solving this programmatically.

Calculating each station's distance introduces a n squared speed step which can certainly cause performance problems.  But if you only calculate the distance between the two systems you are about to present as the top pick that should be fairly quick.  

proposed algorithm:
If the best price match fails (#1s/#1b) the max distance calc then match the second best sell (#2s/#1b) vs best buy and second best buy vs best sell (#1s/#2b). One of those two will probably fail as well, telling you which station is "way out there".  DIsplay the other.  If all three fail (#1s/#1b, #2s/#1b, and #2s/#1b) then consider both seller and buyer stations as "way out there". 
 temporarily black list both #1b and #1s and repeat, or try #3s/#1b and #3b/#1s.

**Comment by Fi0x** [comment]
Calculating only the first distance is also a problem, because If the user selects the next station/commodity, I would have to calculate that one next. This would cause some lag in the UI which I want to avoid.

It's also not safe to say that all failed calculations require stations that are far away, because if station 1 is in colonia, 2 is in the bubble and 3 at sag a, not all of them would need to be blacklisted, even if all 3 distance checks would fail.

So I think I'll stick to the blacklist.

**Comment by Fi0x** [comment]
Blacklist added to version 1.4.6.6
