### ISSUE TITLE
Error 992, Version 1.6.9.7 - when opening reddit or discord config, via the button in settings

### ISSUE THREAD

**Issue by OzDruiD** [Fi0x/EDCT#75]
### Describe the bug
... Settings Buttons to open Discord or Reddit JSON file in editor error with 992 and nothing happens, errors in logs produced.

### To Reproduce
Version 1.6.9.7 - when opening reddit or discord config, via the button in settings
**Steps to reproduce the behavior**:
1. Open EDCT
2. Access Settings via top right cog
3. Attempt to click the Open Reddit Config or Open Discord Config - this does _not_ work.  Errros shown in log (attached).
4.However, Blacklist button WORKS - opens permit systems in notepad, so suspect file assoction or JSON editor not working?

### Expected behavior
... Reddit and Discord Buttons opens some kind of editor with template relevant to discord or reddit? 

### Screenshots
Screenshot of EDCT directory for reference
JSON files are there, however on my system file-associated with Notepad++
Text file of blacklist is there, assocaited with Notepad.

### Additional context
Log files attached

.
[2021-09-23-10-25-48.log](https://github.com/Fi0x/EDCT/files/7227419/2021-09-23-10-25-48.log)
.
![EDCT-Json files exist](https://user-images.githubusercontent.com/20792799/134714923-6ac5264b-21d6-4ca7-89de-6219430d2f7c.JPG)
.

**Comment by Fi0x** [comment]
Hi OzDruiD,
Thanks a lot for reporting this bug!

I was able to reproduce the error on my own machine and found out that it is actually caused by the association with notepad++.
I will try to fix this in the next version, but if you want a solution right now, you can try to change the file-association from notepad++ to the Windows Notepad.

For some reason, the file opens in notepad++ a while after the error occurs (20-40s). Did this happen to you as well?
